/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  docs: [
    'framework',
    // 'overview',
    {
      type: 'link',
      href: 'https://example.com', // Add the URL you want to link to
      label: 'External Link Example',
      // id: "overview",
      // label: 'meri marji',
    },
    {
      type: 'category',
      label: 'Tutorial - Extras',
      link: {
        type: 'generated-index',
        title: 'Tutorial - Extras Title goes here',
        description: 'Learn about the most important Docusaurus concepts!',
        slug: '/tutorial-extras-land',
        keywords: ['guides'],
        // image: '/img/docusaurus.png',
      },
      items: ['tutorial-extras/manage-docs-versions', 'tutorial-extras/translate-your-site', 'tutorial-extras/zksnark-fhe-integration'],
      collapsible : true
    },
  ],

};

export default sidebars;
